# Generated by Django 3.2.8 on 2021-10-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forget_password',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
